### ISSUE TITLE
Missing LICENSE.md file.

### ISSUE THREAD

**Issue by tohagan** [beeman/fireloop-starter#47]
# ![FireLoop](https://storage.googleapis.com/fireloop/fireloop-gh-header.svg)

### What type of issue are you creating?
- [ ] Bug
- [X] Enhancement
- [ ] Question

### What version of this module are you using?
- [ ] 1.0.0-alpha.0
- [ ] pre-alpha
- [ ] other

### Add a description for your issue:

Hopefully it's just the same as the [FireLoop.io Licence](https://github.com/mean-expert-official/fireloop.io/blob/master/LICENSE) but would be nice to have this declared.

Thanks!

- [ ] will submit a pull request

**Comment by beeman** [comment]
Good point @tohagan - I've created a PR for this #48 so it should be added soon!
